### PR TITLE
Clean up master branch

### PR DESCRIPTION
**Pull request by sprice**
The `master` branch was recently brought up to date with `gh-pages`. There are a few things left to do to clean it up.
- Remove some files that are included in `.gitignore` so they are not tracked. `./cumulative.json`, `./doc-data-full.js`, and `./doc-data.js`
- Remove the old video.js source code from `./videojs-src`. The video.js source is now cloned to `./video.js` and is ignored
- Run the grunt task. Doing so updates `./docs/api/js/doc-data.js`

### CODE REVIEW

**Comment by gkatsev** [comment]
Now that PRs are done against master, the grunt task won't be needed to run until we need to do a deploy. Probably makes sense to do now, though.

**Comment by sprice** [comment]
Sounds good. I figured `master` should be kept in a deployable state, but there's no reason it needs to be.

**Comment by gkatsev** [comment]
Deployable doesn't mean deployed. The grunt task feels like the deployment for me. Would also keep the master branch cleaner moving forward.

**Comment by rcrooks** [comment]
agreed -- good changes

Gary Katsevman wrote:

**Pull request merged**
