### PR TITLE
Clarify contribution process

### PR DESCRIPTION
**Pull request by sprice**
Following up on parts of #8, this clarifies that pull requests should happen against `master`, and not `gh-pages`

### CODE REVIEW

**Comment by rcrooks** [comment]
That was written before we had a gh-branch, but let it stand -- ignore 
what I said earlier. Since Gary prefers that we merge PRs into master, 
that's fine with me -- probably is a better idea.

Shawn Price wrote:

**Comment by rcrooks** [comment]
ps. so based on my last reply, will reject this one.

Shawn Price wrote:

**Comment by sprice** [comment]
"Since Gary prefers that we merge PRs into master,
that's fine with me -- probably is a better idea."

This is what this PR accomplishes. Recently, a number of PR's have been integrated directly into `gh-pages`. It seem they should be integrated into `master`. This PR clarifies this point in the Readme.

Based on this I'm not clear why this PR should be rejected. Can you please clarify? Thanks.

**Comment by gkatsev** [comment]
Master isn't currently in a state to accept PRs, I assume.

**Comment by sprice** [comment]
Oh. I may have gotten ahead of myself. I figured the change would be coming soon that synced up master and gh-pages. And once that was in place we could pull this in.

**Comment by sprice** [comment]
Should the sync of `master` and `gh-pages` be done with a PR or directly on `master`? I just tried out `git merge gh-pages -X theirs` on a potential PR but then there is a commit which is `Merge branch 'gh-pages' into MY-BRANCH-NAME` which may not be ideal.

**Comment by rcrooks** [comment]
I'm really a git lightweight, so I am open to the ideas of those who 
know it better. gh-pages is the branch of the doc site. I do think it 
would be better to merge PRs into master, and then update gh-pages from 
master, but I'm not sure what's the best workflow on that. I can update 
the current master branch to what's in gh-pages one way or another.

Shawn Price wrote:

**Comment by sprice** [comment]
#8 has two options to brining `master` up to date with `gh-pages`. Once that is complete and new PR's are happening against `master`, then any time you want to update the docs site you can do the following locally:

```
git checkout master
git pull origin master
git checkout gh-pages
git pull origin gh-pages
git merge master
git push origin gh-pages
```

Note the `origin` remote here is `videojs/docs` which you may call `upstream` or something else.

**Pull request merged**
