### PR TITLE
Fix EXTENDS href

### PR DESCRIPTION
**Pull request by sprice**
The `href` of EXTENDS links isn't working. This fixes it.

Sidenote: if someone could explain the relationship between the `master` and `gh-pages` branches that would help with contributing. It seems to me that `gh-pages` is what matters as that is what serves content. Thanks.

### CODE REVIEW

**Comment by gkatsev** [comment]
`5.0` branch is actually the canonical branch and then it gets merged into gh-pages to deploy.
`5.0` branch really should become master soon.

**Comment by gkatsev** [comment]
Never mind, thought this was on the videojs.com repo. Ignore my previous comment.

**Comment by rcrooks** [comment]
gh-pages is the default branch - don't use master. gh-pages drives the actual  doc website.

**Comment by sprice** [comment]
@rcrooks would it be possible to set `gh-pages` as the default branch in Github settings? I think that would make things more clear.

**Comment by gkatsev** [comment]
I would prefer to make master in-line with gh-pages. Have people PR changes into master which we could then merge into gh-pages when we want to deploy the changes.

**Comment by rcrooks** [comment]
ok

Gary Katsevman wrote:

**Comment by rcrooks** [comment]
Gary, I'm a git lightweight -- gh-pages is way ahead of master at this 
point -- what's the simplest way to get them back in sync?

Gary Katsevman wrote:

**Comment by gkatsev** [comment]
I think that something like this would do it:

``` sh
git checkout master
git merge gh-pages -X theirs
```

What this should tell it to always use the changes from gh-pages when merging.

Another way is to reset the branch to gh-pages:

``` sh
git checkout master
git reset --hard gh-pages
```

**Pull request merged**
